# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/robert/Desktop/大三下课程/计算摄影学/FinalProject-3160103829-王宇琪/Grab_Cut

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/robert/Desktop/大三下课程/计算摄影学/FinalProject-3160103829-王宇琪/Grab_Cut

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/robert/Desktop/大三下课程/计算摄影学/FinalProject-3160103829-王宇琪/Grab_Cut/CMakeFiles /Users/robert/Desktop/大三下课程/计算摄影学/FinalProject-3160103829-王宇琪/Grab_Cut/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/robert/Desktop/大三下课程/计算摄影学/FinalProject-3160103829-王宇琪/Grab_Cut/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Grab_Cut

# Build rule for target.
Grab_Cut: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Grab_Cut
.PHONY : Grab_Cut

# fast build rule for target.
Grab_Cut/fast:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/build
.PHONY : Grab_Cut/fast

src/BorderMatting.o: src/BorderMatting.cpp.o

.PHONY : src/BorderMatting.o

# target to build an object file
src/BorderMatting.cpp.o:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/BorderMatting.cpp.o
.PHONY : src/BorderMatting.cpp.o

src/BorderMatting.i: src/BorderMatting.cpp.i

.PHONY : src/BorderMatting.i

# target to preprocess a source file
src/BorderMatting.cpp.i:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/BorderMatting.cpp.i
.PHONY : src/BorderMatting.cpp.i

src/BorderMatting.s: src/BorderMatting.cpp.s

.PHONY : src/BorderMatting.s

# target to generate assembly for a file
src/BorderMatting.cpp.s:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/BorderMatting.cpp.s
.PHONY : src/BorderMatting.cpp.s

src/GCApplication.o: src/GCApplication.cpp.o

.PHONY : src/GCApplication.o

# target to build an object file
src/GCApplication.cpp.o:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GCApplication.cpp.o
.PHONY : src/GCApplication.cpp.o

src/GCApplication.i: src/GCApplication.cpp.i

.PHONY : src/GCApplication.i

# target to preprocess a source file
src/GCApplication.cpp.i:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GCApplication.cpp.i
.PHONY : src/GCApplication.cpp.i

src/GCApplication.s: src/GCApplication.cpp.s

.PHONY : src/GCApplication.s

# target to generate assembly for a file
src/GCApplication.cpp.s:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GCApplication.cpp.s
.PHONY : src/GCApplication.cpp.s

src/GMM.o: src/GMM.cpp.o

.PHONY : src/GMM.o

# target to build an object file
src/GMM.cpp.o:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GMM.cpp.o
.PHONY : src/GMM.cpp.o

src/GMM.i: src/GMM.cpp.i

.PHONY : src/GMM.i

# target to preprocess a source file
src/GMM.cpp.i:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GMM.cpp.i
.PHONY : src/GMM.cpp.i

src/GMM.s: src/GMM.cpp.s

.PHONY : src/GMM.s

# target to generate assembly for a file
src/GMM.cpp.s:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GMM.cpp.s
.PHONY : src/GMM.cpp.s

src/GUI.o: src/GUI.cpp.o

.PHONY : src/GUI.o

# target to build an object file
src/GUI.cpp.o:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GUI.cpp.o
.PHONY : src/GUI.cpp.o

src/GUI.i: src/GUI.cpp.i

.PHONY : src/GUI.i

# target to preprocess a source file
src/GUI.cpp.i:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GUI.cpp.i
.PHONY : src/GUI.cpp.i

src/GUI.s: src/GUI.cpp.s

.PHONY : src/GUI.s

# target to generate assembly for a file
src/GUI.cpp.s:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GUI.cpp.s
.PHONY : src/GUI.cpp.s

src/GrabCut.o: src/GrabCut.cpp.o

.PHONY : src/GrabCut.o

# target to build an object file
src/GrabCut.cpp.o:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GrabCut.cpp.o
.PHONY : src/GrabCut.cpp.o

src/GrabCut.i: src/GrabCut.cpp.i

.PHONY : src/GrabCut.i

# target to preprocess a source file
src/GrabCut.cpp.i:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GrabCut.cpp.i
.PHONY : src/GrabCut.cpp.i

src/GrabCut.s: src/GrabCut.cpp.s

.PHONY : src/GrabCut.s

# target to generate assembly for a file
src/GrabCut.cpp.s:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/GrabCut.cpp.s
.PHONY : src/GrabCut.cpp.s

src/KmeansSample.o: src/KmeansSample.cpp.o

.PHONY : src/KmeansSample.o

# target to build an object file
src/KmeansSample.cpp.o:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/KmeansSample.cpp.o
.PHONY : src/KmeansSample.cpp.o

src/KmeansSample.i: src/KmeansSample.cpp.i

.PHONY : src/KmeansSample.i

# target to preprocess a source file
src/KmeansSample.cpp.i:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/KmeansSample.cpp.i
.PHONY : src/KmeansSample.cpp.i

src/KmeansSample.s: src/KmeansSample.cpp.s

.PHONY : src/KmeansSample.s

# target to generate assembly for a file
src/KmeansSample.cpp.s:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/KmeansSample.cpp.s
.PHONY : src/KmeansSample.cpp.s

src/graph.o: src/graph.cpp.o

.PHONY : src/graph.o

# target to build an object file
src/graph.cpp.o:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/graph.cpp.o
.PHONY : src/graph.cpp.o

src/graph.i: src/graph.cpp.i

.PHONY : src/graph.i

# target to preprocess a source file
src/graph.cpp.i:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/graph.cpp.i
.PHONY : src/graph.cpp.i

src/graph.s: src/graph.cpp.s

.PHONY : src/graph.s

# target to generate assembly for a file
src/graph.cpp.s:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/graph.cpp.s
.PHONY : src/graph.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/maxflow.o: src/maxflow.cpp.o

.PHONY : src/maxflow.o

# target to build an object file
src/maxflow.cpp.o:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/maxflow.cpp.o
.PHONY : src/maxflow.cpp.o

src/maxflow.i: src/maxflow.cpp.i

.PHONY : src/maxflow.i

# target to preprocess a source file
src/maxflow.cpp.i:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/maxflow.cpp.i
.PHONY : src/maxflow.cpp.i

src/maxflow.s: src/maxflow.cpp.s

.PHONY : src/maxflow.s

# target to generate assembly for a file
src/maxflow.cpp.s:
	$(MAKE) -f CMakeFiles/Grab_Cut.dir/build.make CMakeFiles/Grab_Cut.dir/src/maxflow.cpp.s
.PHONY : src/maxflow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Grab_Cut"
	@echo "... src/BorderMatting.o"
	@echo "... src/BorderMatting.i"
	@echo "... src/BorderMatting.s"
	@echo "... src/GCApplication.o"
	@echo "... src/GCApplication.i"
	@echo "... src/GCApplication.s"
	@echo "... src/GMM.o"
	@echo "... src/GMM.i"
	@echo "... src/GMM.s"
	@echo "... src/GUI.o"
	@echo "... src/GUI.i"
	@echo "... src/GUI.s"
	@echo "... src/GrabCut.o"
	@echo "... src/GrabCut.i"
	@echo "... src/GrabCut.s"
	@echo "... src/KmeansSample.o"
	@echo "... src/KmeansSample.i"
	@echo "... src/KmeansSample.s"
	@echo "... src/graph.o"
	@echo "... src/graph.i"
	@echo "... src/graph.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/maxflow.o"
	@echo "... src/maxflow.i"
	@echo "... src/maxflow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

